version: "3.3"

services:
  mysql:
    image: iaasimov-db
    build: 
      context: ./iaasimov-db
    restart: always
    expose:
      - "3306"
    ports:
      - 3306:3306
    volumes:
      - "/opt/dbdata:/var/lib/mysql"

  grok:
    image: iaasimov-grok
    build:
      context: ./iaasimov-grok
    restart: always
    depends_on:
      - mysql          
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/iaasimov
 

